# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'ExampleWithInterestingLibraries' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleWithInterestingLibraries
  pod 'EasyTipView', '~> 2.1'
  pod 'GrowingTextView', '0.7.2'
  pod 'ActiveLabel'

  target 'ExampleWithInterestingLibrariesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleWithInterestingLibrariesUITests' do
    # Pods for testing
  end

end
