# Uncomment the next line to define a global platform for your project
platform :ios, '14.3'

target 'ExampleWithInterestingLibraries' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleWithInterestingLibraries
  pod 'Apollo'
  pod 'BulletinBoard'
  pod 'GRDB.swift'
  pod 'SkeletonView'
  pod 'KeychainAccess'
  pod 'DropDown'
  pod 'GrowingTextView', '0.7.2'
  pod 'ActiveLabel'

  target 'ExampleWithInterestingLibrariesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleWithInterestingLibrariesUITests' do
    # Pods for testing
  end

end
